### PR TITLE
Removed forced HTTPS

### PR DESCRIPTION
**Pull request by amandiobm**
removed forced HTTPS, now the argument gets the whole server host

### CODE REVIEW

**Comment by danharrin** [comment]
I wonder - would this be a breaking change for people who already have apps set up locally without the `https` in their config?

**Comment by amandiobm** [comment]
I was wondering that too, I think it will be, a new version should be released, the same thing for envault

**Comment by amandiobm** [comment]
@danharrin any update on this?! Can we create a new version?

**Comment by danharrin** [comment]
@amandiobm there's not concept of "versions" with Envault - as people's servers auto-update when changes are made to our repository.

We need to tweak these changes to that they autoprefix `https://` if it's not present in the URL already.

**Comment by danharrin** [comment]
Closing due to inactivity.

**Pull request closed without merging**
